### ISSUE TITLE
IntegrityError when delete posts in admin page.

### ISSUE THREAD

**Issue by Wang-Sen** [vicalloy/LBForum#29]
IntegrityError at /admin/lbforum/post/

(1452, 'Cannot add or update a child row: a foreign key constraint fails (`lpardb`.`lbforum_topic`, CONSTRAINT `lbforum_topic_post_id_2d230e5a_fk_lbforum_post_id` FOREIGN KEY (`post_id`) REFERENCES `lbforum_post` (`id`))')

Request Method: 	POST
Request URL: 	https://lpars.cn.ibm.com/admin/lbforum/post/
Django Version: 	1.10.2
Exception Type: 	IntegrityError
Exception Value: 	

(1452, 'Cannot add or update a child row: a foreign key constraint fails (`lpardb`.`lbforum_topic`, CONSTRAINT `lbforum_topic_post_id_2d230e5a_fk_lbforum_post_id` FOREIGN KEY (`post_id`) REFERENCES `lbforum_post` (`id`))')

Exception Location: 	/usr/lib64/python2.7/site-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable: 	/usr/bin/python
Python Version: 	2.7.8
Python Path: 	

['/usr/lib/python2.7/site-packages/django_bower-5.2.0-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages',
 '/var/www/html/LPAR-reservation-system']

Server time: 	Tue, 1 Nov 2016 15:14:20 +0800

**Comment by vicalloy** [comment]
The post you deleted is topic post, you should delete topic instead of post.

**Comment by Wang-Sen** [comment]
Thanks.  Be confused with post and topic :)
