### ISSUE TITLE
老哥，如何切换到中文版本呢？

### ISSUE THREAD

**Issue by kymo** [vicalloy/LBForum#32]
fyi

**Comment by vicalloy** [comment]
中文翻译在 https://github.com/vicalloy/LBForum/blob/master/lbforum/locale/zh-Hans/LC_MESSAGES/django.po 。翻译信息有段时间没有更新，可能不是太全了。
要设置语言及时区，可以在settings里面把下面的设置加上。
LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = True

**Comment by kymo** [comment]
好的谢谢哈，已经搞定了，谢谢开源~ bbs.souxiaoshuo.cc

2017-05-22 9:10 GMT+08:00 vicalloy <notifications@github.com>:
